name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      CI: true
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Set protoc permissions
      run: |
        find ~/.m2/repository -name "protoc-*exe" -type f -exec chmod +x {} \; 2>/dev/null || true
        find ~/.m2/repository -name "protoc-gen-*exe" -type f -exec chmod +x {} \; 2>/dev/null || true
    
    - name: Run tests
      run: mvn clean test
    
    - name: Build package
      run: mvn package -DskipTests
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: target/surefire-reports/
    
    # Only upload build artifacts on master branch pushes
    - name: Get project version
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      id: version
      run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT
    
    - name: Upload build artifacts
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: actions/upload-artifact@v4
      with:
        name: maven-artifacts-${{ steps.version.outputs.VERSION }}
        path: |
          target/xdagj-p2p-${{ steps.version.outputs.VERSION }}.jar
          target/xdagj-p2p-${{ steps.version.outputs.VERSION }}-sources.jar
          target/xdagj-p2p-${{ steps.version.outputs.VERSION }}-javadoc.jar
          target/xdagj-p2p-${{ steps.version.outputs.VERSION }}-jar-with-dependencies.jar 