name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Ensure protoc executables have proper permissions
      run: |
        find ~/.m2/repository -name "protoc-*exe" -type f -exec chmod +x {} \; 2>/dev/null || true
        find ~/.m2/repository -name "protoc-gen-*exe" -type f -exec chmod +x {} \; 2>/dev/null || true
    
    - name: Run tests
      run: mvn clean test
    
    - name: Generate test report
      run: mvn surefire-report:report-only surefire-report:failsafe-report-only
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          target/surefire-reports/
          target/site/

  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Ensure protoc executables have proper permissions
      run: |
        find ~/.m2/repository -name "protoc-*exe" -type f -exec chmod +x {} \; 2>/dev/null || true
        find ~/.m2/repository -name "protoc-gen-*exe" -type f -exec chmod +x {} \; 2>/dev/null || true
    
    - name: Build package
      run: mvn clean package -DskipTests
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: maven-artifacts
        path: |
          target/xdagj-p2p-*.jar
          !target/xdagj-p2p-*-jar-with-dependencies.jar
          !target/original-*.jar 